
version: '2.1'

services:
  NULL2:
    build: .
    shm_size: 2gb
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/London"
    volumes:
      - "/path/to/config:/config"
    ports:
      - "3000:3000"
